/*
create table trabajador(id_trabajador integer primary key auto_increment,
                       nombre varchar(120), paterno varchar(120), materno varchar(120) );



*/



CREATE TABLE USUARIO (ID_USUARIO INTEGER PRIMARY KEY AUTO_INCREMENT,
           NOMBRE VARCHAR(250), EDAD INTEGER, SUELDO FLOAT);

CREATE TABLE DIRECCION (ID_DIRECCION INTEGER PRIMARY KEY AUTO_INCREMENT,
 ID_USUARIO INTEGER, CALLE VARCHAR(250),CP INTEGER,COLONIA VARCHAR(300), 
ESTADO VARCHAR(200),
   CONSTRAINT FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO));